apps/groupdiscussions/urls.py
from django.urls import path

from . import views

app_name = 'groupdiscussions'

urlpatterns = [
    path('schedule-group-discussion/', views.list_group_discussions, name='list_group_discussions'),
    path('search/group-discussion/', views.search_groupdiscussion, name='search_groupdiscussion'),
    path('online-group-discussion/<slug:slug>/', views.group_discussion_detail, name='group_discussion_detail'),
]

apps/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('payments/gd/enroll/<slug:slug>/', views.enroll_in_groupdiscussion, name='enroll_in_groupdiscussion'),
    path('payments/gd/success/<slug:slug>/', views.payments_for_group_discussion, name='payment_for_group_discussion'),
    path("payments/dashboard/", views.dashboard, name="dashboard"),
    path("payments/pricing/", views.pricing, name="pricing"),
    path("payments/free-booking/<slug:slug>/", views.book_free_service, name="free_booking"),
]

swabhyaas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogsSitemap,StaticViewSitemap,HighPrioritySitemaps


# handler404 = 'apps.common.views.custom_page_not_found'
# handler500 = 'apps.common.views.custom_500_error'

sitemaps = {'static': StaticViewSitemap, 'group-discussion-blogs': BlogsSitemap,'important':HighPrioritySitemaps}


urlpatterns = [
    path('adminra/', admin.site.urls),
    path("", include("apps.common.urls")),
    path("", include("apps.blogs.urls")),
    path("", include("apps.groupdiscussions.urls")),
    path("", include("apps.payments.urls")),
    path("", include("apps.authentication.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/payments/models.py
from jsonfield import JSONField
from django.db import models
from django.conf import settings


class Payment(models.Model):
    status_choice = (("paid","paid"),("failed","failed"),("pending","pending"),("refunded","refunded"))
    mentor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="mentor_payments", help_text="Mentor or Moderator")
    payee = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="mentee_payments", help_text="User who paid")
    group_discussion = models.ForeignKey('groupdiscussions.GroupDiscussion',on_delete=models.CASCADE, related_name="payments")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=10)
    status = models.CharField(max_length=10, choices=status_choice)
    order_id = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100)
    coupon = models.ForeignKey('payments.CouponCode',on_delete=models.SET_NULL, related_name="payments", null=True, blank=True)
    extra = JSONField(null=True, blank=True, default=dict)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural="Payments"

    def __str__(self):
        return self.payee.email + " - " + self.group_discussion.title


class PaymentAttempt(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group_discussion = models.ForeignKey('groupdiscussions.GroupDiscussion',on_delete=models.CASCADE)
    message = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural="Payment Attempts"
    
    def __str__(self):
        return self.user.email + " - " + self.group_discussion.title
    

class CouponCode(models.Model):
    code = models.CharField(max_length=50)
    discount = models.IntegerField()
    expires = models.DateField()
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.code + ' - ' + str(self.discount) + '%'
    

class Referral(models.Model):
    payment = models.OneToOneField('payments.Payment',on_delete=models.CASCADE, related_name="referral")
    referer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="referrals")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural="Referrals"
    
    def __str__(self):
        return self.referer.email + " - " + self.payment.payee.email + " - " + self.payment.group_discussion.title


class Credit(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="credits")
    payment = models.OneToOneField('payments.Payment',on_delete=models.SET_NULL, related_name="credits", blank=True, null=True)
    amount = models.IntegerField()
    reason = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural="Credits"
    
    def __str__(self):
        return self.user.email + " - " + self.reason

apps/payments/views.py
import requests
import razorpay

from django.utils import timezone
from django.shortcuts import render
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

from .utils import get_discounted_amount
from .utils import set_referer, add_referral_credits, deduct_referral_credits, multiplier
from .models import PaymentAttempt, Payment
from apps.payments.templatetags.referral_filter import user_referral_credit
from apps.groupdiscussions.models import GroupDiscussion

if settings.DEBUG:
    razorpay_key = settings.RAZORPAY_TEST_KEY
    razorpay_secret = settings.RAZORPAY_TEST_SECRET_KEY
else:
    razorpay_key = settings.RAZORPAY_LIVE_KEY
    razorpay_secret = settings.RAZORPAY_LIVE_SECRET_KEY

def track_payment_attempt(user, group_discussion, message="attempted"):
    payment_attempt = PaymentAttempt.objects.filter(user=user,group_discussion=group_discussion).first()
    if payment_attempt:
        payment_attempt.updated_at = timezone.now()
        payment_attempt.message = message
        payment_attempt.save()
    else:
        PaymentAttempt.objects.create(user=user,group_discussion=group_discussion,message=message)


@login_required
def enroll_in_groupdiscussion(request, slug):
    group_discussion = GroupDiscussion.objects.get(slug=slug)
    if group_discussion.is_free:
        messages.info(request, "This is a free GD, enrolling with no cost.")
        return redirect('payments:free_booking', slug=slug)
    
    existing_referral_credits = user_referral_credit(request.user)
    if existing_referral_credits >= group_discussion.price:
        messages.info(request, f"Enrolling using your available credits, credits deducted {group_discussion.price}")
        deduct_referral_credits(user=request.user, amount=group_discussion.price)
        return redirect('payments:free_booking', slug=slug)

    coupon_code = request.GET.get("code")
    amount = get_discounted_amount(price=group_discussion.price,code=coupon_code,request=request)
    net_amount = int(amount)
    if existing_referral_credits > 0:
        net_amount = net_amount - multiplier(existing_referral_credits, razorpay_multiplier=100)
        messages.add_message(request, messages.INFO, f"Utilizing available credits: {existing_referral_credits}")

    if net_amount <= 0:
        return redirect('payments:free_booking', slug=slug)
    
    client = razorpay.Client(auth=(razorpay_key, razorpay_secret))
    currency = "INR"
    response = client.order.create({'amount': net_amount,'currency':currency,'payment_capture':1,
                                    "notes":{'gd_title':group_discussion.title,'user_email':request.user.email, "coupon_code":coupon_code,
                                             "referer": request.session.get('referer', None),
                                             "deduct_credit": existing_referral_credits}
                                             })
    
    track_payment_attempt(user=request.user,group_discussion=group_discussion)
    context = {'response':response,'group_discussion':group_discussion,"razorpay_client_key":razorpay_key,'amount':int(net_amount)/100}
    return render(request, 'payments/initialization.html', context=context)


@csrf_exempt
def payments_for_group_discussion(request, slug):
    group_discussion = GroupDiscussion.objects.get(slug=slug)

    if request.method == "GET":
        payment = Payment.objects.filter(payee=request.user,group_discussion=group_discussion).first()
        context = {'payment':payment}
        return render(request, 'payments/payment_status.html', context=context)
    
    if request.method == "POST":
        client = razorpay.Client(auth=(razorpay_key, razorpay_secret))
        razorpay_payment_id = request.POST.get("razorpay_payment_id")
        razorpay_payment = client.payment.fetch(razorpay_payment_id)

        user_email = razorpay_payment['notes'].get('user_email', None)
        payee = User.objects.get(email=user_email)
        coupon_code = razorpay_payment['notes'].get('coupon_code', None)
        
        status = "paid" if razorpay_payment['status'] == 'captured' else "failed"
        payment = Payment.objects.create(mentor=group_discussion.mentor,payee=payee,group_discussion=group_discussion,
                                         amount=razorpay_payment['amount'],currency=razorpay_payment['currency'],
                                         status=status,order_id=razorpay_payment['order_id'],
                                         payment_id=razorpay_payment['id'],
                                         coupon=coupon_code,
                                         extra=razorpay_payment)
        track_payment_attempt(user=payee,group_discussion=group_discussion,message=status)

        referer = razorpay_payment['notes'].get('referer', None)
        set_referer(referer=referer, payment=payment)
        add_referral_credits(referer=referer, payment=payment)
        
        if razorpay_payment['notes'].get('deduct_credit', 0):
            deduct_referral_credits(user=payee, amount=int(razorpay_payment.get('notes').get('deduct_credit', 0)))
            
        requests.post("https://ntfy.sh/fastapi", data=f"New Booking for GroupDiscussion.Co {user_email}.".encode(encoding='utf-8'))
        context = {'payment':payment}
        return render(request, 'payments/payment_status.html', context=context)


@login_required
def dashboard(request):
    payments = Payment.objects.filter(payee=request.user)
    context = {'payments':payments, 'base_domain_url':settings.BASE_DOMAIN_URL}
    return render(request, 'payments/dashboard.html', context=context)


def pricing(request):
    return redirect('groupdiscussions:list_group_discussions')


@login_required
def book_free_service(request, slug: str):
    messages.info(request, "Your booking is confirmed, Kindly do not enroll for the same GD Twice.")
    group_discussion = GroupDiscussion.objects.get(slug=slug)
    payment = Payment.objects.create(mentor=group_discussion.mentor,payee=request.user,group_discussion=group_discussion,
                                     amount=0,currency='INR',status="paid",order_id="free",
                                     payment_id="free",coupon=None,extra={})
    requests.post("https://ntfy.sh/fastapi", data=f"New Free Booking for GroupDiscussion.Co {request.user.email}.".encode(encoding='utf-8'))
    context = {'payment':payment}
    return render(request, 'payments/payment_status.html', context=context)

templates/payments/dashboard.html
{% extends "layouts/base.html" %}

{% block title %}<title>Payments Dashboard</title>{% endblock %}

{% block body %}
<div class="px-4 sm:px-6 lg:px-8">
    <div class="mt-8 flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Index</th>
                  <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Title</th>
                  <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Amount</th>
                  <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Status</th>
                  <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Date Paid</th>
                  <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-white bg-rose-500">Meeting Link</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 bg-white">
                {% for payment in payments %}
                <tr>
                  <td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ forloop.counter }}</td>
                  <td class="py-4 px-3 text-sm text-gray-500">{{ payment.group_discussion.title }}</td>
                  <td class="py-4 px-3 text-sm text-gray-500">{% widthratio payment.amount 100 1 %}</td>
                  <td class="py-4 px-3 text-sm text-gray-500">{{ payment.status }}</td>
                  <td class="py-4 px-3 text-sm text-gray-500">{{ payment.created_at }}</td>
                  <td class="py-4 px-3 text-sm text-gray-500"><a href="{{payment.group_discussion.meeting_url}}" target="_blank" class="text-white bg-rose-500 rounded py-2 px-4">Join Meeting</a></td>
                </tr>
                {% empty %}
                <tr>
                  <td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6" colspan="6">No Bookings found.</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
            <h2 class="mt-8 text-2xl font-semibold tracking-tight text-gray-900">Referral Link</h2>
            <p class="mt-2 text-sm text-gray-500 font-semibold">Share this link with your friends and earn 33% of their payments which you can use to participate in GD or Interview.</p>
            <a href="{% url 'groupdiscussions:list_group_discussions' %}?referer={{ request.user.username }}" class="mt-2 text-sm text-indigo-500">{{base_domain_url}}{% url 'groupdiscussions:list_group_discussions' %}?referer={{ request.user.username }}</a>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/payments/initialization.html
{% extends "layouts/base.html" %}
{% load referral_filter %}

{% block title %}
<title>Enroll in {{group_discussion.title}}</title>
{% endblock %}

{% block body %}
<div class="mx-auto">
    <div class="flex flex-col md:flex-row">

        <div class="w-full md:w-3/4 mt-10 bg-white px-4">
            <h2 class="text-center max-w-lg mb-6 font-sans text-3xl font-bold leading-none tracking-tight text-gray-900 sm:text-4xl md:mx-auto">
                <span class="relative inline-block">
                    <span class="relative text-rose-500">Payment</span>
                </span>
                Page
            </h2>
            <hr class="my-2" />
            <p class="text-base font-bold text-gray-700 md:text-lg text-center mb-5">
                Total Billing Amount: INR {{amount}}
            </p>
            <div class="text-center my-1">
                <input type="checkbox" id="check-terms" />
                I accept the
                <a href="/terms/" target="__blank" class="text-blue-500">Terms</a>
                and
                <a href="/refund-policy/" target="__blank" class="text-blue-500">Refund policy</a>.
                <div id="unchecked-msg" class="text-rose-500 font-semibold"></div>
            </div>

            <div class="text-center max-w-lg mb-6 font-sans font-bold leading-none tracking-tight text-gray-900 sm:text-4xl md:mx-auto">
                <div>
                    <button onclick="coupon_code_toggler()" type="button"
                        class="justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-indigo-500"
                        id="menu-button" aria-expanded="true" aria-haspopup="true">
                        Apply Coupon Code
                    </button>
                </div>

                <div id="coupon-code-box"
                    class="z-20 hidden origin-top-right mx-16 my-2 p-4 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
                    role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
                    <div class="relative">
                        <input type="text" id="coupon-code" name="code"
                            class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    </div>
                    <div id="empty-code"></div>
                    <button
                        class="justify-center rounded-md w-full border border-gray-300 shadow-sm px-4 py-2 bg-yellow-500 text-white text-sm font-medium text-gray-700 hover:bg-gray-800"
                        onclick="submit_coupon_code()">
                        Apply
                    </button>
                </div>
            </div>

            {% if response %}
            <div class="container mx-auto">
              <div class="flex justify-center">
                  <form action="/payments/gd/success/{{group_discussion.slug}}/" method="POST" class="max-w-md mx-auto">
                    <script
                      src="https://checkout.razorpay.com/v1/checkout.js"
                      data-key="{{razorpay_client_key}}"
                      data-amount="{{response.amount}}"
                      data-currency="{{response.currency}}"
                      data-order_id="{{response.id}}"
                      data-buttontext="Pay Now"
                      data-name="GroupDiscussion.Co"
                      data-prefill.name="{{request.user.username}}"
                      data-prefill.email="{{request.user.email}}"
                      data-prefill.contact="00"
                      data-theme.color="#F43F5E"
                    ></script>
                    <input type="hidden" custom="Hidden Element" name="hidden" />
                  </form>
                </div>
            </div>
            {% endif %}
        </div>

        <div class="w-full md:w-1/4 mt-10 bg-rose-100 rounded px-4">
            <section class="text-gray-600 body-font">
                <div class="lg:px-24 px-5 py-8 md:flex-row flex-col items-center">
                    <div class="text-left">
                        <h1 class="font-sans text-xl font-semibold tracking-tight text-rose-500 sm:text-4xl">
                            <span>Referral Credit</span>
                        </h1>
                    </div>
                </div>
            </section>

            <section class="text-gray-600 body-font">
                <div class="sm:prose lg:prose-2xl xl:prose-2xl mx-auto">
                    <p class="text-rose-500">You have {{request.user|user_referral_credit }} INR</p>
                    <p class="mb-5 text-sm font-semibold text-gray-600">Share this link with your friends and earn 33% of their payments which you can use to participate in GD or Interview.</p>
                    <a href="{{base_domain_url}}{% url 'groupdiscussions:list_group_discussions' %}?referer={{ request.user.username }}" class="mb-5 text-sm font-semibold text-rose-500">{{base_domain_url}}{% url 'groupdiscussions:list_group_discussions' %}?referer={{ request.user.username }}</a>
                </div>
            </section>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    payment_button = document.getElementsByClassName("razorpay-payment-button")[0];
    payment_button.className = "razorpay-payment-button w-full h-12 px-16 my-4 font-medium tracking-wide text-white transition duration-200 bg-rose-500 rounded shadow-md hover:bg-gray-900 focus:shadow-outline focus:outline-none mx-auto block";

    var checker = document.getElementById("check-terms");
    checker.onchange = function () {
      if (checker.checked) {
        payment_button.disabled = false;
        document.getElementById("unchecked-msg").innerHTML = "";
      } else {
        payment_button.disabled = true;
      }
    };
  
    payment_button.onclick = function () {
      if (!checker.checked) {
        document.getElementById("unchecked-msg").innerHTML =
        '<p class="text-danger">Please accept the terms and conditions.</p>';
      }
      if (checker.checked) {
        payment_button.disabled = false;
      } else {
        payment_button.disabled = true;
      }
    };
  </script>
  
  <script>
      function coupon_code_toggler(){
        const menu = document.getElementById('coupon-code-box');
        menu.classList.toggle("hidden");
      }
  
      function submit_coupon_code(){
          coupon_code = document.getElementById("coupon-code").value.trim();
          if(coupon_code == ""){
              document.getElementById("empty-code").innerHTML =
              '<p class="text-danger text-sm font-normal">Please enter a coupon code.</p>';
          }
          else{
              window.location.href = window.location.protocol + "//" + window.location.host + window.location.pathname +"?code="+coupon_code;
          }
      }
  </script>  
{% endblock scripts %}

templates/payments/payment_status.html
{% extends "layouts/base.html" %} {% block body %}
<div class="container py-10 px-36 items-center">
  <h2
    class="max-w-full mb-6 font-sans text-3xl font-bold leading-none tracking-tight text-gray-900 sm:text-4xl"
  >
    <span class="relative inline-block">
      <span class="relative text-rose-500">Payment Details</span>
    </span>
  </h2>
  <p class="text-base text-gray-700 md:text-lg">
    This is the information for your payment.
  </p>
  <p class="text-base text-gray-700 md:text-lg">
    Order ID: {{payment.order_id}}
  </p>
  <p class="text-base text-gray-700 md:text-lg">
    Payment ID: {{payment.payment_id}}
  </p>
  <p class="text-base text-gray-700 md:text-lg">
    Amount: {% widthratio payment.amount 100 1 %} {{payment.currency}}
  </p>
  <p class="text-base text-gray-700 md:text-lg">
    Date of Payment: {{payment.updated_at}}
  </p>
  <a href="{% url 'payments:dashboard' %}"
    ><button
      class="text-base font-bold text-white md:text-lg bg-rose-500 rounded py-2 px-4"
    >
      Visit Dashboard
    </button></a
  >

  <h2
    class="mt-5 max-w-full mb-6 font-sans text-3xl font-bold leading-none tracking-tight text-gray-900 sm:text-4xl"
  >
    <span class="relative inline-block">
      <span class="relative text-rose-500"
        >Most frequently asked questions</span
      >
    </span>
  </h2>

  <div class="border rounded shadow-sm">
    <button
      type="button"
      aria-label="Open item"
      title="Open item"
      class="toggle-card w-full p-4 focus:outline-none"
    >
      <p class="text-lg font-medium text-rose-500">
        I have booked 1/3 Month subscription, How to get the schedule for
        meeting?<i class="fas fa-chevron-down ml-3"></i>
      </p>
    </button>
    <div class="p-4 pt-0 hidden">
      <p class="text-gray-700">
        Our team will contact you at your registered email and discuss the
        schedule. You can also contact us at
        <a
          href="mailto:team@groupdiscussion.co"
          class="text-gray-600 transition-colors duration-300 hover:text-rose-500 pt-2"
          >team@groupdiscussion.co</a
        >
        to get a list of meeting schedule.
      </p>
    </div>
  </div>

  <div class="border rounded shadow-sm">
    <button
      type="button"
      aria-label="Open item"
      title="Open item"
      class="toggle-card w-full p-4 focus:outline-none"
    >
      <p class="text-lg font-medium text-rose-500">
        What if I miss the GD schedule?<i class="fas fa-chevron-down ml-3"></i>
      </p>
    </button>
    <div class="p-4 pt-0 hidden">
      <p class="text-gray-700">
        We share your details with our moderators and freeze their slot. So, we
        can't reschedule the same.
      </p>
    </div>
  </div>

  <div class="border rounded shadow-sm">
    <button
      type="button"
      aria-label="Open item"
      title="Open item"
      class="toggle-card w-full p-4 focus:outline-none"
    >
      <p class="text-lg font-medium text-rose-500">
        How many participants will be in the GD?<i
          class="fas fa-chevron-down ml-3"
        ></i>
      </p>
    </button>
    <div class="p-4 pt-0 hidden">
      <p class="text-gray-700">
        We put a cap of maximum 6-8 students. This helps us give sufficient
        review time and minimize the waiting time for review.
      </p>
    </div>
  </div>

  <div class="border rounded shadow-sm">
    <button
      type="button"
      aria-label="Open item"
      title="Open item"
      class="toggle-card w-full p-4 focus:outline-none"
    >
      <p class="text-lg font-medium text-rose-500">
        What will be the topic for the GD?<i
          class="fas fa-chevron-down ml-3"
        ></i>
      </p>
    </button>
    <div class="p-4 pt-0 hidden">
      <p class="text-gray-700">
        We expose the topic only at the time of GD. This helps push your
        boundaries and forces the think instantly.
      </p>
    </div>
  </div>

  <p class="text-sm text-rose-500 mt-2">
    For more FAQs visit : <a href="/faqs/" class="text-indigo-500">FAQ page</a>
  </p>
</div>
{% endblock %} {% block scripts %}
<script>
  const toggleButtons = document.querySelectorAll(".toggle-card");

  toggleButtons.forEach(function (button) {
    button.addEventListener("click", function () {
      const content = button.nextElementSibling;
      content.classList.toggle("hidden");
    });
  });
</script>
{% endblock %}