apps/groupdiscussions/urls.py
from django.urls import path

from . import views

app_name = 'groupdiscussions'

urlpatterns = [
    path('schedule-group-discussion/', views.list_group_discussions, name='list_group_discussions'),
    path('search/group-discussion/', views.search_groupdiscussion, name='search_groupdiscussion'),
    path('online-group-discussion/<slug:slug>/', views.group_discussion_detail, name='group_discussion_detail'),
]

apps/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path('payments/gd/enroll/<slug:slug>/', views.enroll_in_groupdiscussion, name='enroll_in_groupdiscussion'),
    path('payments/gd/success/<slug:slug>/', views.payments_for_group_discussion, name='payment_for_group_discussion'),
    path("payments/dashboard/", views.dashboard, name="dashboard"),
    path("payments/pricing/", views.pricing, name="pricing"),
    path("payments/free-booking/<slug:slug>/", views.book_free_service, name="free_booking"),
]

swabhyaas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogsSitemap,StaticViewSitemap,HighPrioritySitemaps


# handler404 = 'apps.common.views.custom_page_not_found'
# handler500 = 'apps.common.views.custom_500_error'

sitemaps = {'static': StaticViewSitemap, 'group-discussion-blogs': BlogsSitemap,'important':HighPrioritySitemaps}


urlpatterns = [
    path('adminra/', admin.site.urls),
    path("", include("apps.common.urls")),
    path("", include("apps.blogs.urls")),
    path("", include("apps.groupdiscussions.urls")),
    path("", include("apps.payments.urls")),
    path("", include("apps.authentication.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/groupdiscussions/models.py
import requests
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey

from django.db import models
from django.urls import reverse
from django.conf import settings

from apps.third_party_services.zoom_meetings import create_zoom_meeting


class GroupDiscussion(MPTTModel):
    mentor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='group_discussions')
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    small_description = models.CharField(max_length=100, blank=True, null=True)
    description = RichTextUploadingField(config_name='default')
    start_datetime = models.DateTimeField()
    max_students = models.IntegerField(null=True, blank=True)
    enrolled_students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='enrolled_group_discussions', blank=True)
    price = models.IntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_free = models.BooleanField(default=False)
    is_private = models.BooleanField(default=False)
    meeting_id = models.CharField(max_length=100, blank=True, null=True)
    meeting_url = models.CharField(max_length=100, blank=True, null=True)
    meeting_password = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    parent = TreeForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children')

    class Meta:
        ordering = ('start_datetime',)
        verbose_name = 'Group Discussion'
        verbose_name_plural = 'Group Discussions'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('group_discussion_detail', args=[self.slug])
    
    def get_booking_url(self):
        return reverse('group_discussion_booking', args=[self.slug])
    

    def save(self, *args, **kwargs):
        if not self.is_free and not self.price:
            raise ValueError('Price is required for paid group discussions')
        
        if self.is_free and self.price:
            raise ValueError('Price is not required for free group discussions')
        
        if self.id and self.max_students:
            if self.enrolled_students.count() >= self.max_students - 1:
                requests.post("https://ntfy.sh/fastapi", data=f"Near Max Enrollment for Group Discussion {self.id}  {self.title}.".encode(encoding='utf-8'))

        if not self.meeting_id:
            meeting = create_zoom_meeting(self.title, self.start_datetime, 60, self.slug)
            self.meeting_id = meeting['meeting_id']
            self.meeting_url = meeting['meeting_url']
            self.meeting_password = meeting['meeting_password']
        super().save(*args, **kwargs)

apps/groupdiscussions/views.py
from django.shortcuts import render
from django.db.models import Q
from django.db.models import F
from django.db.models import Count
from datetime import datetime

from .models import GroupDiscussion
from apps.analytics.utils import track_hit
from apps.analytics.models import Searches


def list_group_discussions(request):
    """List the active or private group discussions also remove the group discussions with number of enrolled students greater than or equal to max students or start_datetime_date greater than today."""
    track_hit(request)
    print("referer is ",request.session.get('referer', None))
    group_discussions = (
    GroupDiscussion.objects
    .filter(Q(is_active=True) | Q(is_private=True))
    .annotate(enrolled_students_count=Count('enrolled_students'))
    .exclude(enrolled_students_count__gte=F('max_students'))
    .exclude(start_datetime__date__lt=datetime.now().date())
    .exclude(is_private=True)
    ).order_by('tree_id')
    return render(request, 'groupdiscussions/gd_list.html', {'group_discussions': group_discussions})


def group_discussion_detail(request, slug):
    track_hit(request)
    group_discussion = GroupDiscussion.objects.get(slug=slug)
    return render(request, 'groupdiscussions/gd_detail.html', {'group_discussion': group_discussion})


def search_groupdiscussion(request):
    track_hit(request)
    query = request.GET.get('gd', None)
    group_discussions = []
    if query:
        group_discussions = GroupDiscussion.objects.filter(
            Q(title__icontains=query) | Q(small_description__icontains=query),
            is_active=True,
            start_datetime__date__gte=datetime.now().date()
        )
    Searches.objects.create(
        user=request.user if request.user.is_authenticated else None,
        query=query,
        length_results=len(group_discussions)
    )
    return render(request, 'groupdiscussions/gd_list.html', {'group_discussions': group_discussions})

templates/groupdiscussions/gd_detail.html
{% extends "layouts/base.html" %}
{% load referral_filter %}

{% block title %}
<title>{{group_discussion.title}}</title>
{% endblock %}

{% block head %}
<meta name="description" content="{{group_discussion.small_description}}">
<link rel="stylesheet" href="https://unpkg.com/@tailwindcss/typography@0.4.x/dist/typography.min.css" />
{% endblock %}

{% block body %}
<div class="mx-auto">
    <div class="flex flex-col md:flex-row">
        <div class="w-full md:w-3/4 mt-10 bg-white px-4">
            <section class="text-gray-600 body-font">
                <div class="lg:px-24 px-5 py-8 md:flex-row flex-col items-center">
                    <div class="text-center">
                        <h1 class="font-sans text-3xl font-bold tracking-tight text-rose-500 sm:text-4xl">
                            <span>{{group_discussion.title}}</span>
                        </h1>
                    </div>
                </div>
            </section>

            <section class="text-gray-600 body-font">
                <div class="sm:prose lg:prose-2xl xl:prose-2xl mx-auto">
                    <p class="text-rose-500">Price: {{group_discussion.price}} INR</p>
                    <p class="mb-5 text-rose-500">{{group_discussion.start_datetime}} IST</p>
                    <p class="mb-5 text-center">{{group_discussion.description|safe}}</p>
                </div>
            </section>

            <div class="flex justify-center">
                <a href="{% url 'payments:enroll_in_groupdiscussion' group_discussion.slug %}">
                    <button class="bg-rose-500 hover:bg-rose-700 text-white font-bold py-2 px-4 rounded-lg">
                        Enroll Now
                    </button>
                </a>
            </div>            
        </div>
        <!-- small card on right side that displays Referral credit if user is logged in -->
        {% if request.user.is_authenticated %}
        <div class="w-full md:w-1/4 mt-10 bg-rose-100 rounded px-4">
            <section class="text-gray-600 body-font">
                <div class="lg:px-24 px-5 py-8 md:flex-row flex-col items-center">
                    <div class="text-left">
                        <h1 class="font-sans text-xl font-semibold tracking-tight text-rose-500 sm:text-4xl">
                            <span>Referral Credit</span>
                        </h1>
                    </div>
                </div>
            </section>

            <section class="text-gray-600 body-font">
                <div class="sm:prose lg:prose-2xl xl:prose-2xl mx-auto">
                    <p class="text-rose-500">You have {{request.user|user_referral_credit }} INR</p>
                    <p class="mb-5 text-sm font-semibold text-gray-600">Share this link with your friends and earn 33% of their payments which you can use to participate in GD or Interview.</p>
                    <a href="{{base_domain_url}}{% url 'groupdiscussions:list_group_discussions' %}?referer={{ request.user.username }}" class="mb-5 text-sm font-semibold text-rose-500">{{base_domain_url}}{% url 'groupdiscussions:list_group_discussions' %}?referer={{ request.user.username }}</a>
                </div>
            </section>
        </div>
        {% else %}
        <div class="w-full md:w-1/4 mt-10 bg-rose-100 rounded px-4">
            <section class="text-gray-600 body-font">
                <div class="lg:px-24 px-5 py-8 md:flex-row flex-col items-center">
                    <div class="text-left">
                        <h1 class="font-sans text-xl font-semibold tracking-tight text-rose-500 sm:text-4xl">
                            <span>Referral Credit</span>
                        </h1>
                    </div>
                </div>
            </section>

            <section class="text-gray-600 body-font">
                <div class="sm:prose lg:prose-2xl xl:prose-2xl mx-auto">
                    <p class="mb-5 text-sm font-semibold text-gray-600">Login and share your your referral url to earn 33% credits that you can utilize to enroll in GD or PI.</p>
                    <a href="/login/?next={{request.path}}" class="text-white bg-rose-400 text-sm px-4 py-2 rounded">Login</a>
                </div>
            </section>
        {% endif %}
    </div>
</div>
{% endblock %}
        

templates/groupdiscussions/gd_list.html
{% extends "layouts/base.html" %} {% block title %}
<title>Schedule Group Discussions Online</title>
{% endblock %} {% block body %}
<div
  class="flex flex-col lg:flex-row lg:justify-end mt-8 px-2 lg:ml-6 lg:items-center"
>
  <!-- a form to search for group discussions  -->
  <form
    action="{% url 'groupdiscussions:search_groupdiscussion' %}"
    method="GET"
    class="mb-2 lg:mb-0 lg:mr-4 flex items-center"
  >
    <input
      class="rounded-l-lg p-4 border-t border-b text-gray-700 border-gray-200 bg-gray-100"
      placeholder="Search GD/PI"
      name="gd"
      id="search"
      type="text"
    />
    <button
      class="px-4 rounded-r-lg bg-rose-600 ml-0 text-white font-bold p-4 uppercase lg:ml-0 lg:mt-0"
    >
      Search
    </button>
  </form>
  <!-- <a
    href="https://swabhyaas.com/?utm_source=mockinterview&utm_medium=interview_list&referer=sourabh"
    target="_blank"
    class="lg:ml-0"
  >
    <button
      class="px-4 rounded-lg mr-5 bg-gradient-to-r from-rose-500 to-violet-500 ml-0 text-white font-bold p-4 uppercase border-rose-500 border-t border-b border-r"
    >
      Practice GD
    </button>
  </a> -->
</div>

<div class="flex flex-wrap px-5 mt-16">
  {% for groupdiscussion in group_discussions %}
  <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/3 xl:w-1/3 px-4 mb-8">
    <div
      class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700"
    >
      <div class="p-5">
        <a
          href="{% url 'groupdiscussions:group_discussion_detail' groupdiscussion.slug %}"
        >
          <h5
            class="mb-2 text-2xl font-bold tracking-tight text-rose-500 dark:text-white"
          >
            {{groupdiscussion.title}}
          </h5>
        </a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
          {{groupdiscussion.small_description}}
        </p>
        <a
          href="{% url 'groupdiscussions:group_discussion_detail' groupdiscussion.slug %}"
          class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-rose-500 rounded-lg hover:bg-rose-800 focus:ring-4 focus:outline-none focus:ring-rose-300 dark:bg-rose-600 dark:hover:bg-rose-700 dark:focus:ring-rose-800"
        >
          Schedule Now
          <svg
            class="rtl:rotate-180 w-3.5 h-3.5 ms-2"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 14 10"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M1 5h12m0 0L9 1m4 4L9 9"
            />
          </svg>
        </a>
      </div>
    </div>
  </div>
  {% empty %}
  <div class="w-full px-4 mb-8">
    <div
      class="bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700"
    >
      <div class="p-5">
        <h5
          class="mb-2 text-2xl font-bold tracking-tight text-rose-500 dark:text-white"
        >
          All Slots are currently Booked.
        </h5>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
          Kindly
          <a href="mailto:team@groupdiscussion.co" class="text-indigo-500"
            >mail team@groupdiscussion.co</a
          >
          or
          <a
            href="https://wa.me/918936891514?text=Need%20a%20Mock%20Interview%20on%20_"
            target="_blank"
            class="text-indigo-500"
            >WhatsApp</a
          >
          with your interview name and preferred date, time. We will definitely
          try to open up a Interview slot and share with you ASAP.
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}